# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['HelloSayer', 'say_hello']

# Cell
class HelloSayer:
    "Say hello `to` using `say_hello`"
    def __init__(self, to): self.to = to

    def say(self):
        "Do the saying"
        return say_hello(self.to)

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'